class ForzaCoreApi(Exception):
    ...

class DatabaseException(ForzaCoreApi):
    ...

class DuplicateException(DatabaseException):
    ...

class NotFoundException(Exception):
    ...

class UserException(ForzaCoreApi):
    ...

class UserNotFoundException(NotFoundException):
    ...

class UserAlreadyDeactivatedException(UserException):
    ...

class StockMovementNotFoundException(NotFoundException):
    ...

class ProductNotFoundException(NotFoundException):
    ...

class CategoryNotFoundException(NotFoundException):
    ...

class CategoryInActiveException(ForzaCoreApi):
    ...

class InventoryNotFoundException(NotFoundException):
    ...
    
class SupplierNotFoundException(NotFoundException):
    ...

class SupplierInActiveException(ForzaCoreApi):
    ...

class InvalidBarcodeException(ForzaCoreApi):
    ...

class PurchaseOrderException(ForzaCoreApi):
    ...
    
class PurchaseOrderNotFoundException(NotFoundException):
    ...

class PurchaseOrderItemNotFoundException(NotFoundException):
    ...

class PurchaseOrderSupplierInactiveException(PurchaseOrderException):
    ...

class PurchaseOrderStatusException(PurchaseOrderException):
    ...
    
class SaleNotFoundException(NotFoundException):
    ...

class SaleItemNotFoundException(NotFoundException):
    ...
