class ForzaCoreApi(Exception):
    ...

class DatabaseException(ForzaCoreApi):
    ...

class DuplicateException(DatabaseException):
    ...

class NotFoundException(Exception):
    ...

class UserNotFoundException(NotFoundException):
    ...

class StockMovementNotFoundException(NotFoundException):
    ...

class ProductNotFoundException(NotFoundException):
    ...

class CategoryNotFoundException(NotFoundException):
    ...

class SupplierNotFoundException(NotFoundException):
    ...